import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <a href="https://nextjs.org"></a>
        </h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque commodi modi ad soluta temporibus tempora, nesciunt libero corrupti odio eaque nulla possimus ipsa obcaecati ex enim id voluptatibus quasi recusandae.
        </p>
      </main>
    </>
  );
}
